[ADD] add antropismo filters in monitoring
hexgis/cmr2_painel pull request #11
Opened 2022-06-03 19:28 UTC by GabrielMarianosf

add antropismo filters in monitoring

2022-06-03 19:30 UTC, GabrielMarianosf commented
![](https://github.trello.services/images/mini-trello-icon.png) [Antropismo Consolidado](https://trello.com/c/xGyKeyCM/6-antropismo-consolidado)

2022-06-03 19:30 UTC, GabrielMarianosf commented
![](https://github.trello.services/images/mini-trello-icon.png) [Antropismo Consolidado](https://trello.com/c/xGyKeyCM/6-antropismo-consolidado)

2022-06-04 22:01 UTC, dagnaldo requested changes

2022-06-04 22:01 UTC, dagnaldo commented on pages/index/monitoring.vue
> +            <!-- <div class="tab-header justify-space-between">
please, remove unecessary comments.

2022-06-04 22:01 UTC, dagnaldo commented on pages/index/monitoring.vue
> +            <!-- <v-container>
please, remove unecessary comments.

2022-06-04 22:01 UTC, dagnaldo commented on pages/index/monitoring.vue
> +        },
Missing blank line.

2022-06-04 22:01 UTC, dagnaldo commented on pages/index/monitoring.vue
> +        orderedSupportLayersGroups() {
Missing blank line.

2022-06-04 22:01 UTC, dagnaldo commented on pages/index/monitoring.vue
> +        ]),
Missing blank line.

2022-06-04 22:01 UTC, dagnaldo commented on store/supportLayers.js
> +    activeLayerIds(state) {
Missing blank line.

2022-06-06 18:05 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersAntropismo.vue
> +                            :required="true"
Yes, resolved.

2022-06-06 18:05 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersAntropismo.vue
> +    mounted() {
Resolved.

2022-06-06 18:05 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersAntropismo.vue
> +    watch: {
Resolved.

2022-06-06 18:05 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersAntropismo.vue
> +        filterLayer() {
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersAntropismo.vue
> +            console.log(this.filters)
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on components/support/SupportLayersGroupItemAntropismo.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on pages/index/monitoring.vue
> +            <!-- <v-container>
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on pages/index/monitoring.vue
> +        orderedSupportLayersGroups() {
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on pages/index/monitoring.vue
> +        ]),
Resolved.

2022-06-06 18:06 UTC, GabrielMarianosf commented on store/supportLayers.js
> +    activeLayerIds(state) {
Resolved.

2022-06-10 20:13 UTC, dagnaldo approved these changes

2022-06-23 12:23 UTC, merged