Feature/prodes
hexgis/cmr2_painel pull request #12
Opened 2022-06-03 19:29 UTC by GabrielMarianosf

ADD filter prodes

2022-06-03 19:31 UTC, GabrielMarianosf commented
![](https://github.trello.services/images/mini-trello-icon.png) [PRODES](https://trello.com/c/NPBKY5Aj/7-prodes)

2022-06-11 01:17 UTC, dagnaldo requested changes

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
only `required` does not works?

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
only required does not works?

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
only `required` does not works?

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
only `required` does not works?

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    mounted() {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    mounted() {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    watch: {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    watch: {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    computed: {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayerFiltersProdes.vue
> +    computed: {
Missing blank line.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayersGroupItemProdes.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Remove unecessary comments.

2022-06-11 01:17 UTC, dagnaldo commented on components/support/SupportLayersGroupItemProdes.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Remove unecessary comments.

2022-06-11 01:17 UTC, dagnaldo commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Missing blank line between mutations.

2022-06-11 01:17 UTC, dagnaldo commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Missing blank line between mutations.

2022-06-11 01:17 UTC, dagnaldo commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Check all occurences.

2022-06-11 01:17 UTC, dagnaldo commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Check all occurences.

2022-06-14 17:33 UTC, GabrielMarianosf commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Resolved.

2022-06-14 17:33 UTC, GabrielMarianosf commented on store/supportLayers.js
> +    setSupportCategoryGroupsProdes(state, categoryGroups) {
Resolved.

2022-06-14 17:33 UTC, GabrielMarianosf commented on components/support/SupportLayersGroupItemProdes.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Resolved.

2022-06-14 17:33 UTC, GabrielMarianosf commented on components/support/SupportLayersGroupItemProdes.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Resolved.

2022-06-14 17:34 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
Resolved.

2022-06-14 17:34 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
Resolved

2022-06-14 17:34 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
Resolved.

2022-06-14 17:34 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +                        :required="true"
Resolved.

2022-06-14 17:35 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +    computed: {
Resolved.

2022-06-14 17:35 UTC, GabrielMarianosf commented on components/support/SupportLayerFiltersProdes.vue
> +    computed: {
Resolved.

2022-06-14 17:35 UTC, GabrielMarianosf commented on components/support/SupportLayersGroupItemProdes.vue
> +            <!-- <v-list-item-action v-if="disabledHeatmap">
Resolved.

2022-06-14 17:42 UTC, GabrielMarianosf commented on pages/index/support-prodes.vue
> +import _ from 'lodash'
Yes, in the ordersSupportLayersGroups method, lodash's sortBy function is used to sort groups and layers based on order property.

2022-06-23 12:39 UTC, merged