Feature/alert structure
hexgis/cmr2_painel pull request #13
Opened 2022-06-08 17:08 UTC by GabrielMoreschi

Foram adicionados o filtro por TI, CR e Data.
A tabela está estruturada e condicionada a requisição retornar dados, que atualmente está implementada porém sem retorno. Aguardando o backend.

2022-06-08 17:09 UTC, GabrielMoreschi commented
![](https://github.trello.services/images/mini-trello-icon.png) [ALERTA URGENTE - Criação do módulo de mapa e tabela](https://trello.com/c/dwUBKSVC/20-alerta-urgente-cria%C3%A7%C3%A3o-do-m%C3%B3dulo-de-mapa-e-tabela)

2022-06-09 15:11 UTC, dagnaldo requested changes
Check the variables, store and component names to work with more descriptive names.

TIP: functions have to be separated by blank line.
TIP2: Centralize CR and TI requests in a store (It will help you to write less code)

2022-06-09 15:11 UTC, dagnaldo commented on components/alert-urg/AlertFilter.vue
> +        ...mapActions('alert-urg', ['getFilterOptions', 'downloadGeoJson']),
urgent-alerts

2022-06-09 15:11 UTC, dagnaldo commented on components/alert-urg/AlertFilter.vue
> +        ...mapMutations('alert-urg', ['setFilters']),
urgent-alerts

2022-06-09 15:11 UTC, dagnaldo commented on store/alert-urg.js
> +    setLoadingCSV(state, payload) {
Missing whitespace between functions

2022-06-09 15:11 UTC, dagnaldo commented on store/alert-urg.js
> +    async getDataTable({ commit, state, rootGetters }) {
Missing blank line between functions

2022-06-10 13:18 UTC, GabrielMoreschi commented on pages/index.vue
> +        "alert-urg-tab": "Alerta Urgente",
Resolved

2022-06-10 13:18 UTC, GabrielMoreschi commented on pages/index.vue
> +        "alert-urg-tab": "Alert Urgent",
Resolved

2022-06-10 13:18 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +                this.$store.commit('alert-urg/setHeatMap', value)
Resolved

2022-06-10 13:19 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +                this.$store.commit('alert-urg/setOpacity', value)
Resolved

2022-06-10 13:19 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +        ...mapActions('alert-urg', ['getFilterOptions', 'downloadGeoJson']),
Resolved

2022-06-10 13:19 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +            if (cr) this.$store.dispatch('alert-urg/getTiOptions', cr)
Resolved

2022-06-10 13:19 UTC, GabrielMoreschi commented on pages/index.vue
> +                    name: this.$t('alert-urg-tab'),
Resolved

2022-06-10 13:20 UTC, GabrielMoreschi commented on store/alert-urg.js
> +    setLoadingCSV(state, payload) {
Resolved

2022-06-10 13:20 UTC, GabrielMoreschi commented on store/alert-urg.js
> +    setLoadingGeoJson(state, payload) {
Resolved

2022-06-10 13:21 UTC, GabrielMoreschi commented on store/alert-urg.js
> +    async getDataTable({ commit, state, rootGetters }) {
Resolved

2022-06-11 01:04 UTC, dagnaldo requested changes

2022-06-11 01:04 UTC, dagnaldo commented on components/alert-urg/AlertFilter.vue
> +    watch: {
Add blank line.

2022-06-11 01:04 UTC, dagnaldo commented on components/alert-urg/AlertFilter.vue
> +    computed: {
Add blank line.

2022-06-11 01:04 UTC, dagnaldo commented on pages/index.vue
> +        "urgent-alerts-tab": "Alert Urgent",
Urgent Alert

2022-06-13 14:13 UTC, GabrielMoreschi commented on pages/index.vue
> +        "urgent-alerts-tab": "Alert Urgent",
Resolved

2022-06-13 14:13 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +    computed: {
Resolved

2022-06-13 14:13 UTC, GabrielMoreschi commented on components/alert-urg/AlertFilter.vue
> +    watch: {
Resolved

2022-06-13 18:06 UTC, dagnaldo approved these changes
Well well, sir.
better late than never...

2022-06-13 18:14 UTC, merged