[CMR-71] SO upload limited
hexgis/cmr2_painel pull request #28
Opened 2022-07-07 13:32 UTC by GabrielMoreschi

Foi criada uma função que identifica o sistema operacional do usuário e limita visualmente as opções de arquivos para utilizar na ferramenta de upload.

2022-07-07 14:16 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
> +            name: '',
Resolved

2022-07-07 20:11 UTC, dagnaldo requested changes
Check suggestions from daily meeting.

2022-07-08 17:45 UTC, GabrielMoreschi commented
> Check suggestions from daily meeting.

Resolved

2022-07-13 13:55 UTC, dagnaldo commented on components/map/file-loader/FileLoaderControl.vue
> +        ...mapActions('map', ['changeStyle', 'saveToDatabase']),
Save to database is working?

2022-07-14 12:30 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
>          loadKmzFile(evt, name) {
Resolved

2022-07-14 12:31 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
> +        saveIntoDb(index) {
Resolved

2022-07-14 13:05 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
> +                                <ConfirmButton
Resolved

2022-07-14 13:12 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
> +            const geoJson = omnivore.kml.parse(evt.result).toGeoJSON()
yes

2022-07-14 13:12 UTC, GabrielMoreschi commented on components/map/file-loader/FileLoaderControl.vue
> +        ...mapActions('map', ['changeStyle', 'saveToDatabase']),
removed

2022-07-14 17:27 UTC, dagnaldo requested changes

2022-07-14 17:27 UTC, dagnaldo commented on components/map/file-loader/FileLoaderControl.vue
> +        saveIntoDb(index) {
Is it in use?

2022-07-14 18:22 UTC, dagnaldo approved these changes

2022-07-14 18:27 UTC, merged