[CMR-81]Feature/filter years land use
hexgis/cmr2_painel pull request #32
Opened 2022-07-13 19:42 UTC by GabrielMoreschi

[CMR-81] - Land-use filter:

Foi adicionado o filtro por ano de acordo com os filtros de CR e TI.

2022-07-13 23:04 UTC, dagnaldo commented on store/land-use.js
> +    }
What is this identation?

2022-07-13 23:04 UTC, dagnaldo commented on store/land-use.js
> +
identation?

2022-07-13 23:04 UTC, dagnaldo commented on components/land-use/LandUseFilter.vue
> +            if (ti) this.$store.dispatch('land-use/getYearsOptions', ti)
Where is the loader?

2022-07-15 14:01 UTC, GabrielMoreschi commented on components/land-use/LandUseFilter.vue
> +            if (ti) this.$store.dispatch('land-use/getYearsOptions', ti)
Resolved

2022-07-15 14:09 UTC, GabrielMoreschi commented on store/land-use.js
> +
Resolved

2022-07-15 18:22 UTC, dagnaldo requested changes
More descriptive variables.

2022-07-15 18:22 UTC, dagnaldo commented on components/land-use/LandUseFilter.vue
> +            loading: false,
Loading what?

2022-07-21 17:01 UTC, GabrielMoreschi commented on components/land-use/LandUseFilter.vue
> +            loading: false,
Resolved

2022-07-21 17:21 UTC, dagnaldo requested changes

2022-07-21 17:21 UTC, dagnaldo commented on components/land-use/LandUseFilter.vue
> +            loadingYears: false,
isLoadingYears... 
Please follow the pattern.

2022-07-25 13:03 UTC, dagnaldo approved these changes

2022-07-25 13:03 UTC, merged