Feature/upload files
hexgis/cmr2_painel pull request #41
Opened 2022-09-02 14:43 UTC by GabrielMoreschi

Foi criado o componente visual de upload de arquivos do módulo documental.

2022-09-06 13:58 UTC, guigawiller commented on components/document-dialog/DocumentUploadDialog.vue
> +            "date-label": "Date of Document",
Check if this is properly written.

2022-09-06 14:04 UTC, guigawiller commented on package.json
> +        "vue-resource": "^1.5.3",
Is this really necessary?

2022-09-06 14:07 UTC, guigawiller requested changes

2022-09-06 14:07 UTC, guigawiller commented on store/document.js
> +
Remove blank line

2022-09-06 14:43 UTC, GabrielMoreschi commented on components/document-dialog/DocumentUploadDialog.vue
> +            "date-label": "Date of Document",
Resolved

2022-09-06 14:50 UTC, GabrielMoreschi commented on store/document.js
> +
Resolved

2022-09-06 14:50 UTC, GabrielMoreschi commented on package.json
> +        "vue-resource": "^1.5.3",
No.
Resolved.

2022-09-21 12:39 UTC, guigawiller requested changes

2022-09-21 12:39 UTC, guigawiller commented on components/document-dialog/DocumentUploadDialog.vue
> +                        Cancelar
Try putting this in the i18n pattern.

2022-09-21 12:39 UTC, guigawiller commented on components/document-dialog/DocumentUploadDialog.vue
> +                        Salvar
Try putting this in the i18n pattern.

2022-09-21 12:48 UTC, GabrielMoreschi commented on components/document-dialog/DocumentUploadDialog.vue
> +                        Salvar
Resolved

2022-09-21 12:55 UTC, guigawiller approved these changes

2022-09-21 12:55 UTC, merged